trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'
  targetFramework: 'net8.0'

stages:
  - stage: Build
    displayName: Build (Debug) and run tests
    dependsOn: []
    pool: 
      vmImage: 'windows-latest'
    jobs:
      - job: Build
        displayName: Build (Debug) and run tests
        steps:
        - task: DotNetCoreCLI@2
          displayName: "Restore packages"
          inputs:
            command: 'restore'
            feedsToUse: 'config'
            nugetConfigPath: '$(Build.SourcesDirectory)\Nuget.config'
            projects: '**/*.sln'

        - task: VSBuild@1
          inputs:
            solution: '$(solution)'
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'

        - task: DotNetCoreCLI@2
          displayName: "Test"
          inputs:
            command: 'test'
            projects: '**/*.sln'
            
        - task: DotNetCoreCLI@2
          displayName: "Restore packages"
          inputs:
            command: 'restore'
            feedsToUse: 'config'
            nugetConfigPath: '$(Build.SourcesDirectory)\Nuget.config'
            projects: '**/*.sln'            
            
        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: 'src\vcsparser\bin\$(buildConfiguration)\$(targetFramework)'
            artifactName: 'vcsparser'
            