//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vcsparser.unittests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vcsparser.unittests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change 144545 on 2018/07/04 by teamcity@build.agent &apos;comments1&apos;
        ///Change 144544 on 2018/07/04 by teamcity@build.agent &apos;comments1&apos;
        ///Change 144541 on 2018/07/04 by teamcity@build.agent &apos;comments with spaces 2&apos;
        ///Change 144540 on 2018/07/04 by teamcity@build.agent &apos;comments with spaces 2&apos;
        ///Change 144538 on 2018/07/04 by teamcity@build.agent &apos;comments with spaces 2&apos;
        ///Change 144537 on 2018/07/04 by teamcity@build.agent &apos;comments with spaces 2&apos;
        ///Change 144535 on 2018/07/04 by user1@user1_workspace &apos;comments with sp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChangesFiles1 {
            get {
                return ResourceManager.GetString("ChangesFiles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change 141284 by author.name@author.name_workspace-machine on 2018/06/29 18:57:47
        ///
        ///	Long description of the change set
        ///
        ///Affected files ...
        ///
        ///... //depot/Dir1/Dir2/EntityModel/AuctionNotification.cpp#4 edit
        ///... //depot/Dir1/Dir2/EntityModel/map/MapContextVehicleProviderComponent.cpp#4 edit
        ///... //depot/Dir1/Dir2/EntityModel/StuntParty/StuntPartyHudCountdownComponent.cpp#9 edit
        ///... //depot/Dir1/Dir2/UI5/UIHelpers.cpp#132 edit
        ///... //depot/Dir1/Dir2/UI5/UIHelpers.h#72 edit
        ///
        ///Differences ...
        ///
        ///==== //d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DescribeFile1 {
            get {
                return ResourceManager.GetString("DescribeFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change .
        /// </summary>
        internal static string DescribeFile2 {
            get {
                return ResourceManager.GetString("DescribeFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change 141284 by author.nameauthoar.name_workspace-machine on 2018/06/29 18:57:47.
        /// </summary>
        internal static string DescribeFile3 {
            get {
                return ResourceManager.GetString("DescribeFile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change 141284 by author.name@authoar.name_workspace-machine on ASDF ASDF.
        /// </summary>
        internal static string DescribeFile4 {
            get {
                return ResourceManager.GetString("DescribeFile4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commit 82419fcdc1fca1f8b14905366159837bfe8a1be4
        ///Author:     Author Name &lt;author@email.com&gt;
        ///AuthorDate: 2018-09-19T14:19:14+01:00
        ///Commit:     Author Name &lt;author@email.com&gt;
        ///CommitDate: 2018-09-19T14:19:14+01:00
        ///
        ///    Commit message 1
        ///    
        ///    * Long description 1 line 1
        ///    * Long description 1 line 2
        ///
        ///1	1	src/dir1/File1.cs
        ///10	1	src/dir1/File2.cs
        ///1	10	src/dir1/File3.cs
        ///
        ///commit 31b45b8417418c3562d19eab8830ed786ac40f40
        ///Author:     Author Name &lt;author@email.com&gt;
        ///AuthorDate: 2018-09-18T16:48:22+01:00
        ///Commit:      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GitExample1 {
            get {
                return ResourceManager.GetString("GitExample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commit 82419fcdc1fca1f8b14905366159837bfe8a1be4
        ///Author:     Author Name &lt;author@email.com&gt;
        ///AuthorDate: 2018-09-19T14:19:14+01:00
        ///Commit:     Author Name &lt;author@email.com&gt;
        ///CommitDate: 2018-09-19T14:19:14+01:00
        ///
        ///    Commit message 1
        ///
        ///-	-	src/dir1/File1.cs
        ///.
        /// </summary>
        internal static string GitExample2 {
            get {
                return ResourceManager.GetString("GitExample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commit a6050ba9b8a09b972193832395fa51b3ca582068
        ///Author:     Eric Lemes &lt;ericlemes@gmail.com&gt;
        ///AuthorDate: 2018-10-02 14:24:42 +0100
        ///Commit:     Eric Lemes &lt;ericlemes@gmail.com&gt;
        ///CommitDate: 2018-10-02 14:24:42 +0100
        ///
        ///    Adds new test1 with 3 lines.
        ///
        ///3	0	test1.txt
        ///
        ///commit cdd4e75b9228de601391c216c7f02eb13006f4c1
        ///Author:     Eric Lemes &lt;ericlemes@gmail.com&gt;
        ///AuthorDate: 2018-10-02 14:24:17 +0100
        ///Commit:     Eric Lemes &lt;ericlemes@gmail.com&gt;
        ///CommitDate: 2018-10-02 14:24:17 +0100
        ///
        ///    Renates test1 to test2
        ///
        ///0	0	t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GitExample3 {
            get {
                return ResourceManager.GetString("GitExample3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GitExample4 {
            get {
                return ResourceManager.GetString("GitExample4", resourceCulture);
            }
        }
    }
}
