//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p4codechurn.unittests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("p4codechurn.unittests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change 144545 on 2018/07/04 by teamcity@build.agent &apos;comments1&apos;
        ///Change 144544 on 2018/07/04 by teamcity@build.agent &apos;comments1&apos;
        ///Change 144541 on 2018/07/04 by teamcity@build.agent &apos;comments with spaces 2&apos;
        ///Change 144540 on 2018/07/04 by teamcity@build.agent &apos;comments with spaces 2&apos;
        ///Change 144538 on 2018/07/04 by teamcity@build.agent &apos;comments with spaces 2&apos;
        ///Change 144537 on 2018/07/04 by teamcity@build.agent &apos;comments with spaces 2&apos;
        ///Change 144535 on 2018/07/04 by user1@user1_workspace &apos;comments with sp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChangesFiles1 {
            get {
                return ResourceManager.GetString("ChangesFiles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change 141284 by author.name@author.name_workspace-machine on 2018/06/29 18:57:47
        ///
        ///	Long description of the change set
        ///
        ///Affected files ...
        ///
        ///... //depot/Dir1/Dir2/EntityModel/AuctionNotification.cpp#4 edit
        ///... //depot/Dir1/Dir2/EntityModel/map/MapContextVehicleProviderComponent.cpp#4 edit
        ///... //depot/Dir1/Dir2/EntityModel/StuntParty/StuntPartyHudCountdownComponent.cpp#9 edit
        ///... //depot/Dir1/Dir2/UI5/UIHelpers.cpp#132 edit
        ///... //depot/Dir1/Dir2/UI5/UIHelpers.h#72 edit
        ///
        ///Differences ...
        ///
        ///==== //d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DescribeFile1 {
            get {
                return ResourceManager.GetString("DescribeFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change .
        /// </summary>
        internal static string DescribeFile2 {
            get {
                return ResourceManager.GetString("DescribeFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change 141284 by author.nameauthoar.name_workspace-machine on 2018/06/29 18:57:47.
        /// </summary>
        internal static string DescribeFile3 {
            get {
                return ResourceManager.GetString("DescribeFile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change 141284 by author.name@authoar.name_workspace-machine on ASDF ASDF.
        /// </summary>
        internal static string DescribeFile4 {
            get {
                return ResourceManager.GetString("DescribeFile4", resourceCulture);
            }
        }
    }
}
